"""Make description unique and non-nullable in Category

Revision ID: 1d1473e5b65c
Revises: f6a379a310af
Create Date: 2024-12-14 12:21:32.255314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1473e5b65c'
down_revision: Union[str, None] = 'f6a379a310af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uq_user_category_name', 'categories', type_='unique')
    op.create_unique_constraint('uq_user_category_name_description', 'categories', ['user_id', 'name', 'description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_category_name_description', 'categories', type_='unique')
    op.create_unique_constraint('uq_user_category_name', 'categories', ['user_id', 'name'])
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
