"""Initial migration

Revision ID: f6a379a310af
Revises: 
Create Date: 2024-12-12 17:23:04.981504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a379a310af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), unique=True, nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    
    # Modify `hashed_password` to be nullable
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.String(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'profile_picture')
    
    # Revert `hashed_password` to NOT NULL
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###
